version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    assignees:
      - "fwilhe"
    schedule:
      interval: 'weekly'
#    allow: 'production'
    commit-message:
      prefix: 'fix(dep):'
